changesDir: .changes
unreleasedDir: unreleased
headerPath: header.tpl.md
changelogPath: CHANGELOG.md
versionExt: md
versionFormat: '## {{.Version}} - {{.Time.Format "2006-01-02"}}'
kindFormat: '### {{.Kind}}'
changeFormat: '* {{.Body}}{{if .Custom.Issue}} ([#{{.Custom.Issue}}](https://github.com/desertwitch/slog-seq/issues/{{.Custom.Issue}})){{end}}{{if .Custom.PR}} ([#{{.Custom.PR}}](https://github.com/desertwitch/slog-seq/pull/{{.Custom.PR}})){{end}}'
kinds:
    - label: Added
      auto: minor
    - label: Changed
      auto: major
    - label: Deprecated
      auto: minor
    - label: Removed
      auto: major
    - label: Fixed
      auto: patch
    - label: Security
      auto: patch
newlines:
    afterChangelogHeader: 1
    beforeChangelogVersion: 1
    endOfVersion: 1
envPrefix: CHANGIE_
custom:
  - key: Issue
    label: Issue Number
    type: int
    minInt: 1
    optional: true
  - key: PR
    label: PR Number
    type: int
    minInt: 1
    optional: true
