name: golang-tests
on:
  push:
    branches:
      - master
      - main
      - devel
  pull_request:
permissions:
  contents: read
jobs:
  slogseq:
    name: test (slogseq)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
          cache: false
      - name: Run tests
        run: go test -failfast -race -covermode=atomic ./...

  seqotel:
    name: test (seqotel)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: 'seqotel/go.mod'
          cache: false
      - name: Run tests
        run: cd seqotel && go test -failfast -race -covermode=atomic ./...
