name: golang-coverage
on:
  push:
    branches:
      - master
      - main
  pull_request:
permissions:
  contents: read
jobs:
  golang:
    name: coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
          cache: false

      - name: Run all Go tests
        run: make test-coverage

      - uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: desertwitch/slog-seq
